### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'click' of null

### ISSUE THREAD

**Issue by GastonGonzalez** [peregrine-cms/page-transition-speed#1]
```
$ node index.js https://docs.peregrine-cms.com / /content/sites/peregrinedocs/slivers/tech/deployment/deploying-peregrine-on-gke-with-helm.html
pts <domain> <path1> <path2>
(node:1983) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'click' of null
    at /Users/gaston/headwire3/workspace/page-transition-speed/index.js:48:31
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:1983) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1983) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by GastonGonzalez** [comment]
This issue was resolved by adding the relative URL of _path2_ as anchor tag to the _path1_ page.
